// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLr1vZMJmCkJIPLYzv7NzyXwszka9pEYc',
    appId: '1:110857450903:web:5a8b8aab6b1448c3d340d2',
    messagingSenderId: '110857450903',
    projectId: 'notice-board-343dd',
    authDomain: 'notice-board-343dd.firebaseapp.com',
    storageBucket: 'notice-board-343dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsNFvPYYHgN81XQ8-_cm1SvkEZkufm0Gw',
    appId: '1:110857450903:android:6b133b150dff79bcd340d2',
    messagingSenderId: '110857450903',
    projectId: 'notice-board-343dd',
    storageBucket: 'notice-board-343dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjF8C8vmrFJoRE6MXJwfEwyxpJZ0FJkQ',
    appId: '1:110857450903:ios:f28ec3f79b1c6126d340d2',
    messagingSenderId: '110857450903',
    projectId: 'notice-board-343dd',
    storageBucket: 'notice-board-343dd.appspot.com',
    iosClientId: '110857450903-91g8nbfojr8hplrcm8sr6k2ardi91g2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.noticeBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjF8C8vmrFJoRE6MXJwfEwyxpJZ0FJkQ',
    appId: '1:110857450903:ios:f28ec3f79b1c6126d340d2',
    messagingSenderId: '110857450903',
    projectId: 'notice-board-343dd',
    storageBucket: 'notice-board-343dd.appspot.com',
    iosClientId: '110857450903-91g8nbfojr8hplrcm8sr6k2ardi91g2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.noticeBoard',
  );
}
